# Site settings
title: Piotr's Home Page
description: No description, yet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://pjtom.dev" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Piotr J. Tomaszewski
user_description: TBD
user_title: Software Developer
# email: 
email_base64: Y29udGFjdEBwanRvbS5kZXYK
# twitter_username: lorem_ipsum
github_username:  PiotrJTomaszewski
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
